site/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webapp.urls', namespace="webapp")),
    url(r'^contas/', include('allauth.urls')),
    url(r'^tarefas/', include('tasklist.api.urls', namespace="tasklist-api")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

site/tasklist/api/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
    TaskListAPIView,
    TaskAPIView,
    TaskCreateAPIView,
    TaskCreate2APIView,
    TaskDetailAPIView,
    TaskDeleteAPIView,
    TaskUpdateAPIView,
)

urlpatterns = [
    url(r'^list/$', TaskListAPIView.as_view(), name='list'),
    url(r'^list2/$', TaskAPIView.as_view(), name='list2'),
    url(r'^create/$', TaskCreateAPIView.as_view(), name='create'),
    url(r'^create2/$', TaskCreate2APIView.as_view(), name='create2'),
    url(r'^(?P<uuid>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})/$', TaskDetailAPIView.as_view(), name='detailUUID'), # SHM Serializer Hypelinked Method
    url(r'^(?P<uuid>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})/edit/$', TaskUpdateAPIView.as_view(), name='updateUUID'),
    url(r'^(?P<uuid>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})/delete/$', TaskDeleteAPIView.as_view(), name='deleteUUID'),

]

site/webapp/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from .views import HomePageView

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
]

site/webapp/models.py
from django.db import models

# Create your models here.

site/webapp/views.py
from django.contrib.auth import get_user_model
from django.views.generic import TemplateView

User = get_user_model()

class HomePageView(TemplateView):
    template_name = "webapp/home.html"

site/templates/webapp/snippets/head.html
<head>
    <title>{% block head_title %}Demos{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1;" charset="UTF-8" />
    <meta name="robots" content="follow">

    <meta name="description" content="Demonstrativo de Webapps">
    <meta name="author" content="lfniederauer">
    <meta name="copyright" content="2018">
    <meta name="keywords" content="Muitas keywords com certeza.">
    <meta itemprop="image" content="">
    <meta property="og:site_name"          content="LFNIEDERAUER DEMO">
    <meta property="og:title"              content="Demonstrativo de Webapps" />
    <meta property="og:description"        content="Demonstrativo de Webapps />
    <meta property="og:locale"             content="pt_BR" />
    <meta property="fb:app_id"             content="">
    <meta property="og:type"               content="website" />

    <meta name="twitter:site" content="">
    <meta name="twitter:creator" content="">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="">
    <meta name="twitter:description" content="Explore o demo">
    <meta name="twitter:image" content="">
</head>

site/templates/webapp/snippets/header.html
{% load staticfiles %}
{% load account %}
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Supero</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'tasklist-api:list' %}">Lista</a></li>
                <li><a href="{% url 'tasklist-api:list2' %}">Lista REST</a></li>
            </ul>
            {% if request.user.is_authenticated %}
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/contas/logout">{% if user.username == None %}UserX{% else %}{{ user.username }}{% endif %}</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'tasklist-api:create' %}">Nova Task</a></li>
            </ul>
            {% else %}
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/contas/login">Login</a></li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>
<!-- Messages -->
{% if messages %}
<div class="container">
    {% for message in messages %}
    <div class="alert {{ message.tags }}" role="alert">
        <button type="button" class="close " data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>

        <div class="media">
                <span class="d-flex g-mr-10 g-mt-5">
                  <i class="icon-info g-font-size-15"></i>
                </span>
            <span class="media-body align-self-center">
                  {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Importante: {% endif %}
                  {{ message }}
                </span>
        </div>
    </div>
    {% endfor %}
</div>
<!-- End Messages -->
{% endif %}
</header>
<!-- End Header -->