site/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webapp.urls', namespace="webapp")),
    url(r'^contas/', include('allauth.urls')),
    url(r'^tarefas/', include('tasklist.api.urls', namespace="tasklist-api")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

site/tasklist/api/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
    TaskListAPIView,
    TaskAPIView,
    TaskCreateAPIView,
    TaskCreate2APIView,
    TaskDetailAPIView,
    TaskDeleteAPIView,
    TaskUpdateAPIView,
)

urlpatterns = [
    url(r'^list/$', TaskListAPIView.as_view(), name='list'),
    url(r'^list2/$', TaskAPIView.as_view(), name='list2'),
    url(r'^create/$', TaskCreateAPIView.as_view(), name='create'),
    url(r'^create2/$', TaskCreate2APIView.as_view(), name='create2'),
    url(r'^(?P<uuid>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})/$', TaskDetailAPIView.as_view(), name='detailUUID'), # SHM Serializer Hypelinked Method
    url(r'^(?P<uuid>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})/edit/$', TaskUpdateAPIView.as_view(), name='updateUUID'),
    url(r'^(?P<uuid>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})/delete/$', TaskDeleteAPIView.as_view(), name='deleteUUID'),

]

site/tasklist/models.py
import datetime
import requests, uuid
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Task(models.Model):
  uuid        = models.UUIDField(default=uuid.uuid4, editable=False)
  taskname    = models.CharField(max_length=60, blank=False, null=False)
  description = models.CharField(max_length=120, blank=False, null=False)
  content     = models.TextField(max_length=120, blank=False, null=False)
  due_date    = models.DateTimeField(auto_now=False, blank=True, null=True, auto_now_add=False)
  finished    = models.BooleanField(default=False, blank=False, null=False)
  finished_date = models.DateTimeField(auto_now=False, blank=True, null=True, auto_now_add=False)
  updated     = models.DateTimeField(auto_now=True, auto_now_add=False)
  created     = models.DateTimeField(auto_now_add=True)
  active      = models.BooleanField(default=True, blank=False, null=False)
  deletion_date = models.BooleanField(default=False, blank=False, null=False)

  def __str__(self):
    return self.taskname

  def get_api_url(self):
    return reverse("tasklist-api:detailUUID", kwargs={"uuid": self.uuid})

  def was_published_recently(self):
    return self.updated >= timezone.now() - datetime.timedelta(days=1)

  class Meta:
    ordering = ('-created',)
    verbose_name_plural = 'Tasks'

site/tasklist/forms.py
from allauth.account.forms import SignupForm
from django import forms

from django.contrib.auth import (
    get_user_model,
    authenticate,
)

# from .models import PerfilPF
# from .utils.Validator_CPF import CPF

User = get_user_model()


class userForm(forms.ModelForm):
    username =  forms.CharField(label='Usuário', max_length='14', required=True)
    first_name =  forms.CharField(label='Primeiro Nome', max_length='30', required=True)
    last_name =  forms.CharField(label='Último Nome', max_length='40', required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name')


class perfilForm(forms.ModelForm):
    cpf         = forms.CharField(label='CPF', max_length='14', required=True)
    mobile      = forms.CharField(label='Celular', max_length='15', required=True)

    def clean_cpf(self):
        # Check that the two password entries match
        cpf = self.cleaned_data.get("cpf")
        cpf = CPF(cpf)
        print(cpf)
        valid = cpf.isValid()
        print(valid)
        if valid != True:
            raise forms.ValidationError("CPF inválido")
        return cpf

        # if check = :
        #     raise forms.ValidationError("Emails não coincidem")
        # return email
        # print("CPF é: " + ckeck)
    class Meta:
        model = PerfilPF
        fields = [
            # 'owner',
            'cpf',
            'mobile',
        ]
    def save(self, commit=True):
        # Save the provided password in hashed format
        form = super(PerfilPF, self).save(commit=False)
        if commit:
            form.save()
        return form

site/tasklist/api/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import get_object_or_404, Http404, redirect
from tasklist.models import Task

from rest_framework.views import APIView
from rest_framework.generics import (
    CreateAPIView,
    DestroyAPIView,
    ListAPIView,
    UpdateAPIView,
    RetrieveAPIView,
    RetrieveDestroyAPIView,
    RetrieveUpdateAPIView,
    ListCreateAPIView,
)

from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly,
)
from rest_framework.renderers import (
    TemplateHTMLRenderer,
    HTMLFormRenderer,
    BrowsableAPIRenderer,
    )

from rest_framework.response import Response

from .serializers import (
    TaskCreateSerializer,
    TaskUpdateSerializer,
    TaskDetailSerializer,
    TaskListSerializer,
    TaskDeleteSerializer,
    )

User = get_user_model()


class TaskListAPIView(APIView):
    permission_classes = (IsAuthenticated,)
    renderer_classes = (TemplateHTMLRenderer,)
    template_name = 'tasklist/task-list-api.html'
    #
    def get(self, request):
        qs = Task.objects.all()
        serializer = TaskListSerializer(qs, many=True)
        return Response({'serializer': serializer, 'tasks': qs})


class TaskAPIView(ListAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskListSerializer
    permission_classes = (IsAuthenticated,)



class TaskCreateAPIView(CreateAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskCreateSerializer
    renderer_classes = (TemplateHTMLRenderer,)
    template_name = 'tasklist/task-create-api.html'

    def get(self, request, format=None):
        serializer = TaskCreateSerializer()
        return Response({'serializer': serializer})

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        messages.success(request, 'Task criada!')
        return redirect('tasklist-api:list')

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)


class TaskCreate2APIView(CreateAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskCreateSerializer


class TaskDetailAPIView(RetrieveAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskDetailSerializer
    # lookup_field = 'uuid'
    renderer_classes = (TemplateHTMLRenderer,)
    template_name = 'tasklist/task-detail-api.html'

    def get(self, request, *args, **kwargs):
        task_obj = self.get_object()
        serializer = self.get_serializer(task_obj)
        return Response({'serializer': serializer, 'context': task_obj})

    def get_object(self, *args, **kwargs):
        uuid = self.kwargs.get("uuid")
        return get_object_or_404(Task, uuid=uuid)


class TaskUpdateAPIView(LoginRequiredMixin, RetrieveUpdateAPIView):
    queryset = Task.objects.all() #is_active
    serializer_class = TaskUpdateSerializer
    renderer_classes = (TemplateHTMLRenderer,)
    template_name = 'tasklist/task-update-api.html'

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        serializer = self.get_serializer(instance)
        return Response({'serializer': serializer, 'instance': instance})

    def get_object(self, *args, **kwargs):
        uuid = self.kwargs.get("uuid")
        return get_object_or_404(Task, uuid=uuid)

    def update(self, request, *args, **kwargs):
        partial = kwargs.pop('partial', True)
        instance = self.get_object()
        serializer = self.get_serializer(instance, data=request.data, partial=partial)
        serializer.is_valid(raise_exception=True)
        self.perform_update(serializer)
        if getattr(instance, '_prefetched_objects_cache', None):
            instance._prefetched_objects_cache = {}
        messages.success(request, 'Sua task foi atualizada')
        return Response({'serializer': serializer, 'instance': instance, 'messages': messages})
        # return Response(serializer.data)


class TaskDeleteAPIView(RetrieveDestroyAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskDeleteSerializer
    renderer_classes = (TemplateHTMLRenderer,)
    template_name = 'tasklist/task-delete-api.html'

    def get_object(self, *args, **kwargs):
        uuid = self.kwargs.get("uuid")
        try:
            return Task.objects.get(uuid=uuid)
        except:
            messages.warning(self.request, 'Task não encontrada!')
            return redirect('tasklist-api:list')

    def perform_destroy(self, instance):
        instance.delete()

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)

    def destroy(self, request, *args, **kwargs):
        try:
            instance = self.get_object()
            self.perform_destroy(instance)
            messages.error(request, 'Task apagada!')
            return redirect('tasklist-api:list')
        except:
            return redirect('tasklist-api:list')

site/templates/tasklist/task-create-api.html
{% extends 'webapp/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load rest_framework %}

{% block head_title %}{% trans "Nova Task" %}{% endblock %}

{% block header %}

{%include 'webapp/snippets/header.html' %}

{% endblock header %}

{% block content %}
<main>
    <section class="container" style="min-height: 50vh">
        <div class="row justify-content-center">
            <div
            ">
            <header class="text-center mb-4">
                <h2 class="h2">{% trans "Nova Task" %}</h2>
            </header>
            <!-- Form -->
            <form action="{{ request.get_full_path }}" method="POST" enctype="multipart/form-data"
                  class='content-markdown' novalidate>
                <fieldset>
                    {% csrf_token %}
                    {% render_form serializer %}
                    <input class='btn btn-primary' type='submit' value='Criar'>
                </fieldset>
            </form>
            <!-- End Form -->
        </div>
        </div>
    </section>
</main>
{% endblock content %}

{% block endjs %}
    <script>
        window.drf = {
          csrfHeaderName: "{{ csrf_header_name|default:'X-CSRFToken' }}",
          csrfToken: "{% if request %}{{ csrf_token }}{% endif %}"
        };
    </script>
    <script src="{% static "rest_framework/js/ajax-form.js" %}"></script>
    <script src="{% static "rest_framework/js/csrf.js" %}"></script>
    <script src="{% static "rest_framework/js/default.js" %}"></script>
    <script>
        $(document).ready(function() {
          $('form').ajaxForm();
        });
    </script>
{% endblock endjs %}

site/templates/tasklist/task-delete-api.html
{% extends 'webapp/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load rest_framework %}

{% block head_title %}{% trans "Atualizar" %}{% endblock %}
{% block header %}
{%include 'webapp/snippets/header.html' %}
{% endblock header %}
{% block content %}
<main>
    <section class="container" style="min-height: 50vh">
        <div class="row justify-content-center">
            <form class="button-form" action="{{ request.get_full_path }}" data-method="delete" novalidate>
                <button class="btn btn-danger">Delete</button>
            </form>
            <p></p>
        </div>
    </section>

</main>
{% endblock content %}
{% block endjs %}
    <script>
        window.drf = {
          csrfHeaderName: "{{ csrf_header_name|default:'X-CSRFToken' }}",
          csrfToken: "{% if request %}{{ csrf_token }}{% endif %}"
        };
    </script>
    <script src="{% static "rest_framework/js/ajax-form.js" %}"></script>
    <script src="{% static "rest_framework/js/csrf.js" %}"></script>
    <script src="{% static "rest_framework/js/default.js" %}"></script>
    <script>
        $(document).ready(function() {
          $('form').ajaxForm();
        });
    </script>
{% endblock endjs %}

site/templates/tasklist/task-detail-api.html
{% extends 'webapp/base.html' %}
{% load staticfiles %}
{% block head_title %}{{ block.super }}{% endblock head_title%}
{% block header %}
{%include 'webapp/snippets/header.html' %}
{% endblock header %}

{% block content %}

<section class="container" style="min-height: 50vh">
    <div class="jumbotron">
        <h1>{{ context.taskname }}</h1>
        <p>Descrição: {{ context.description }}</p>

        <p>Conteúdo: {{ context.content }}</p>
        <p>Finaliza em: {{ context.due_date }}</p>
        <p>Finalizado?
            {% if context.finished == False %}
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            {% else %}
            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
            {% endif %}
        </p>
        <p>Última atualização: {{ context.updated }}</p>
        <p>Data de criação: {{ context.created }}</p>
        <p><a href="{% url 'tasklist-api:updateUUID' context.uuid %}" role="button" class="btn btn-primary btn-lg">Update
            Task</a></p>
        <p><a href="{% url 'tasklist-api:deleteUUID' context.uuid %}" role="button" class="btn btn-primary btn-lg">Apagar
            Task</a></p>
    </div>
</section>
{% endblock content %}

site/templates/tasklist/task-list-api.html
{% extends 'webapp/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load rest_framework %}

{% block header %}
{%include 'webapp/snippets/header.html' %}
{% endblock header %}

{% block content %}
<main>
    <section class="container-fluid" style="min-height: 50vh">
        {% for task in tasks %}
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading"><a href="{% url 'tasklist-api:detailUUID' task.uuid %}">{{ task.taskname }}</a>
            </div>
            <div class="panel-body">
                <p>Descrição: {{ task.description }}</p>
            </div>

            <!-- List group -->
            <ul class="list-group">
                <li class="list-group-item">Conteúdo: {{ task.content }}</li>
                <li class="list-group-item">Terminou?
                    {% if task.finished == False %}
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    {% else %}
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                    {% endif %}
                </li>
                <li class="list-group-item">Atualizado em: {{ task.updated }}</li>
                <li class="list-group-item">Finaliza em: {{ task.due_date }}</li>
                <li class="list-group-item">Criado em: {{ task.created }}</li>
                <li class="list-group-item"><a href="{% url 'tasklist-api:updateUUID' task.uuid %}">Editar</a></li>
                <li class="list-group-item"><a href="{% url 'tasklist-api:deleteUUID' task.uuid %}">Apagar</a></li>
            </ul>
        </div>
        {% endfor %}
    </section>
</main>
{% endblock content %}

{% block endjs %}
    <script>
        window.drf = {
          csrfHeaderName: "{{ csrf_header_name|default:'X-CSRFToken' }}",
          csrfToken: "{% if request %}{{ csrf_token }}{% endif %}"
        };
    </script>
    <script src="{% static "rest_framework/js/ajax-form.js" %}"></script>
    <script src="{% static "rest_framework/js/csrf.js" %}"></script>
    <script src="{% static "rest_framework/js/default.js" %}"></script>
    <script>
        $(document).ready(function() {
          $('form').ajaxForm();
        });
    </script>
{% endblock endjs %}

site/templates/tasklist/task-update-api.html
{% extends 'webapp/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load rest_framework %}

{% block head_title %}{% trans "Atualizar" %}{% endblock %}
{% block header %}
    {%include 'webapp/snippets/header.html' %}
{% endblock header %}
{% block content %}
    <main>
    <section class="container g-pt-20 g-pb-40" style="min-height: 50vh">
      <div class="row justify-content-center">
        <div class="col-sm-8 col-lg-6">
          <div class="g-brd-around g-brd-gray-light-v4 rounded g-py-20 g-px-30">
              <header class="text-center mb-4">
              <h2 class="h2 g-color-black g-font-weight-600">{% trans "Atualizar Task" %}</h2>
            </header>

            <!-- Form -->
            <form action="{{ request.get_full_path }}" data-method="PUT" class='content-markdown' enctype="multipart/form-data" novalidate>
            <!--<form action="{{ request.get_full_path }}" data-method="PUT" class='content-markdown' enctype="multipart/form-data" novalidate>-->
                {% csrf_token %}
                {% render_form serializer %}
                <input class='btn btn-primary' type='submit' value='Atualizar' >
            </form>
            <!-- End Form -->
          </div>
        </div>
      </div>
    </section>

    </main>
{% endblock content %}

{% block endjs %}
      <script>
        window.drf = {
          csrfHeaderName: "{{ csrf_header_name|default:'X-CSRFToken' }}",
          csrfToken: "{% if request %}{{ csrf_token }}{% endif %}"
        };
      </script>
      <script src="{% static "rest_framework/js/jquery-3.3.1.min.js" %}"></script>
      <script src="{% static "rest_framework/js/ajax-form.js" %}"></script>
      <script src="{% static "rest_framework/js/csrf.js" %}"></script>
      <script src="{% static "rest_framework/js/default.js" %}"></script>
      <script>
        $(document).ready(function() {
          $('form').ajaxForm();
        });
      </script>
{% endblock endjs %}